# pip install mkdocs mkdocs-material
# mkdocs serve
# mkdocs gh-deploy

site_name: Circuit
repo_name: Circuit
repo_url: https://github.com/slackhq/circuit
site_description: "A Compose-driven architecture for Android apps"
site_author: Slack
remote_branch: gh-pages

copyright: 'Copyright &copy; 2022 Slack Technologies, LLC'

theme:
  name: 'material'
  favicon: images/slack_logo_small.png
  logo: images/slack_logo.png
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'white'
      accent: 'yellow'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'black'
      accent: 'yellow'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'Lato'
    code: 'Fira Code'

extra_css:
  - 'css/app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.emoji
  - tables
  - admonition

nav:
  - 'Introduction': index.md
  - 'Setting up Circuit': setup.md
  - 'States and Events': states-and-events.md
  - 'Screen': screen.md
  - 'CircuitContent': circuit-content.md
  - 'Navigation': navigation.md
  - 'Presenter': presenter.md
  - 'Ui': ui.md
  - 'Testing': testing.md
  - 'Factories': factories.md
  - 'Code Generation': code-gen.md
  - 'Interop': interop.md
  - 'API':
      - 'circuit-runtime': api/0.x/circuit/com.slack.circuit.runtime/index.html
      - 'circuit-runtime-presenter': api/0.x/circuit/com.slack.circuit.runtime.presenter/index.html
      - 'circuit-runtime-ui': api/0.x/circuit/com.slack.circuit.runtime.ui/index.html
      - 'circuit-foundation': api/0.x/circuit/com.slack.circuit.foundation/index.html
      - 'circuit-overlay': api/0.x/circuit-overlay/com.slack.circuit.overlay/index.html
      - 'circuit-retained': api/0.x/circuit-retained/com.slack.circuit.retained/index.html
      - 'circuit-test': api/0.x/circuit-test/com.slack.circuit.test/index.html
      - 'circuit-codegen-annotations': api/0.x/circuit-codegen-annotations/com.slack.circuit.codegen.annotations/index.html
      - 'backstack': api/0.x/backstack/com.slack.circuit.backstack/index.html
  - 'Discussions ‚èè': https://github.com/slackhq/circuit/discussions
  - 'Change Log': changelog.md
  - 'Contributing': contributing.md
  - 'CoC': code-of-conduct.md